/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'apps-account-address-management': RouteRecordInfo<'apps-account-address-management', '/apps/account/address-management', Record<never, never>, Record<never, never>>,
    'apps-account-auth-management': RouteRecordInfo<'apps-account-auth-management', '/apps/account/auth-management', Record<never, never>, Record<never, never>>,
    'apps-account-fund-overview': RouteRecordInfo<'apps-account-fund-overview', '/apps/account/fund-overview', Record<never, never>, Record<never, never>>,
    'apps-account-personalization': RouteRecordInfo<'apps-account-personalization', '/apps/account/personalization', Record<never, never>, Record<never, never>>,
    'apps-data-center-inventory-data': RouteRecordInfo<'apps-data-center-inventory-data', '/apps/data-center/inventory-data', Record<never, never>, Record<never, never>>,
    'apps-data-center-return-inventory': RouteRecordInfo<'apps-data-center-return-inventory', '/apps/data-center/return-inventory', Record<never, never>, Record<never, never>>,
    'apps-data-center-sales-analysis': RouteRecordInfo<'apps-data-center-sales-analysis', '/apps/data-center/sales-analysis', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-begin': RouteRecordInfo<'apps-drop-shipping-begin', '/apps/drop-shipping/begin', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-order-batch': RouteRecordInfo<'apps-drop-shipping-order-batch', '/apps/drop-shipping/order/batch', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-order-create': RouteRecordInfo<'apps-drop-shipping-order-create', '/apps/drop-shipping/order/create', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-order-list': RouteRecordInfo<'apps-drop-shipping-order-list', '/apps/drop-shipping/order/list', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-order-label-create': RouteRecordInfo<'apps-drop-shipping-order-label-create', '/apps/drop-shipping/order-label/create', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-order-label-list': RouteRecordInfo<'apps-drop-shipping-order-label-list', '/apps/drop-shipping/order-label/list', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-package-batch': RouteRecordInfo<'apps-drop-shipping-package-batch', '/apps/drop-shipping/package/batch', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-package-create': RouteRecordInfo<'apps-drop-shipping-package-create', '/apps/drop-shipping/package/create', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-package-list': RouteRecordInfo<'apps-drop-shipping-package-list', '/apps/drop-shipping/package/list', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-return-order-batch': RouteRecordInfo<'apps-drop-shipping-return-order-batch', '/apps/drop-shipping/return/order-batch', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-return-order-create': RouteRecordInfo<'apps-drop-shipping-return-order-create', '/apps/drop-shipping/return/order-create', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-return-order-list': RouteRecordInfo<'apps-drop-shipping-return-order-list', '/apps/drop-shipping/return/order-list', Record<never, never>, Record<never, never>>,
    'apps-drop-shipping-return-package-list': RouteRecordInfo<'apps-drop-shipping-return-package-list', '/apps/drop-shipping/return/package-list', Record<never, never>, Record<never, never>>,
    'apps-print-label-batch-upload': RouteRecordInfo<'apps-print-label-batch-upload', '/apps/print-label/batch-upload', Record<never, never>, Record<never, never>>,
    'apps-print-label-create': RouteRecordInfo<'apps-print-label-create', '/apps/print-label/create', Record<never, never>, Record<never, never>>,
    'apps-print-label-order-detail-id': RouteRecordInfo<'apps-print-label-order-detail-id', '/apps/print-label/order-detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-print-label-order-new-detail-id': RouteRecordInfo<'apps-print-label-order-new-detail-id', '/apps/print-label/order-new-detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-print-label-orders': RouteRecordInfo<'apps-print-label-orders', '/apps/print-label/orders', Record<never, never>, Record<never, never>>,
    'apps-print-label-shipping-list': RouteRecordInfo<'apps-print-label-shipping-list', '/apps/print-label/shipping-list', Record<never, never>, Record<never, never>>,
    'apps-product-batch': RouteRecordInfo<'apps-product-batch', '/apps/product/batch', Record<never, never>, Record<never, never>>,
    'apps-product-create': RouteRecordInfo<'apps-product-create', '/apps/product/create', Record<never, never>, Record<never, never>>,
    'apps-product-list': RouteRecordInfo<'apps-product-list', '/apps/product/list', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
  }
}
