/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<
      '$error',
      '/:error(.*)',
      { error: ParamValue<true> },
      { error: ParamValue<false> },
      | never
    >,
    'access-control': RouteRecordInfo<
      'access-control',
      '/access-control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-account-address-management': RouteRecordInfo<
      'apps-account-address-management',
      '/apps/account/address-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-account-auth-management': RouteRecordInfo<
      'apps-account-auth-management',
      '/apps/account/auth-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-account-fund-overview': RouteRecordInfo<
      'apps-account-fund-overview',
      '/apps/account/fund-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-account-personalization': RouteRecordInfo<
      'apps-account-personalization',
      '/apps/account/personalization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-account-tiktok-service': RouteRecordInfo<
      'apps-account-tiktok-service',
      '/apps/account/tiktok-service',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-data-center-inventory-data': RouteRecordInfo<
      'apps-data-center-inventory-data',
      '/apps/data-center/inventory-data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-data-center-return-inventory': RouteRecordInfo<
      'apps-data-center-return-inventory',
      '/apps/data-center/return-inventory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-data-center-sales-analysis': RouteRecordInfo<
      'apps-data-center-sales-analysis',
      '/apps/data-center/sales-analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-begin': RouteRecordInfo<
      'apps-drop-shipping-begin',
      '/apps/drop-shipping/begin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-order-batch': RouteRecordInfo<
      'apps-drop-shipping-order-batch',
      '/apps/drop-shipping/order/batch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-order-create': RouteRecordInfo<
      'apps-drop-shipping-order-create',
      '/apps/drop-shipping/order/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-order-detail': RouteRecordInfo<
      'apps-drop-shipping-order-detail',
      '/apps/drop-shipping/order/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-order-list': RouteRecordInfo<
      'apps-drop-shipping-order-list',
      '/apps/drop-shipping/order/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-order-label-create': RouteRecordInfo<
      'apps-drop-shipping-order-label-create',
      '/apps/drop-shipping/order-label/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-order-label-detail': RouteRecordInfo<
      'apps-drop-shipping-order-label-detail',
      '/apps/drop-shipping/order-label/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-order-label-list': RouteRecordInfo<
      'apps-drop-shipping-order-label-list',
      '/apps/drop-shipping/order-label/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-package-batch': RouteRecordInfo<
      'apps-drop-shipping-package-batch',
      '/apps/drop-shipping/package/batch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-package-create': RouteRecordInfo<
      'apps-drop-shipping-package-create',
      '/apps/drop-shipping/package/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-package-detail': RouteRecordInfo<
      'apps-drop-shipping-package-detail',
      '/apps/drop-shipping/package/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-package-list': RouteRecordInfo<
      'apps-drop-shipping-package-list',
      '/apps/drop-shipping/package/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-return-order-batch': RouteRecordInfo<
      'apps-drop-shipping-return-order-batch',
      '/apps/drop-shipping/return/order-batch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-return-order-create': RouteRecordInfo<
      'apps-drop-shipping-return-order-create',
      '/apps/drop-shipping/return/order-create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-return-order-detail': RouteRecordInfo<
      'apps-drop-shipping-return-order-detail',
      '/apps/drop-shipping/return/order-detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-return-order-list': RouteRecordInfo<
      'apps-drop-shipping-return-order-list',
      '/apps/drop-shipping/return/order-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-drop-shipping-return-package-list': RouteRecordInfo<
      'apps-drop-shipping-return-package-list',
      '/apps/drop-shipping/return/package-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-print-label-batch-upload': RouteRecordInfo<
      'apps-print-label-batch-upload',
      '/apps/print-label/batch-upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-print-label-create': RouteRecordInfo<
      'apps-print-label-create',
      '/apps/print-label/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-print-label-order-detail-id': RouteRecordInfo<
      'apps-print-label-order-detail-id',
      '/apps/print-label/order-detail/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'apps-print-label-order-new-detail-id': RouteRecordInfo<
      'apps-print-label-order-new-detail-id',
      '/apps/print-label/order-new-detail/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'apps-print-label-orders': RouteRecordInfo<
      'apps-print-label-orders',
      '/apps/print-label/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-print-label-shipping-list': RouteRecordInfo<
      'apps-print-label-shipping-list',
      '/apps/print-label/shipping-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-product-batch': RouteRecordInfo<
      'apps-product-batch',
      '/apps/product/batch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-product-create': RouteRecordInfo<
      'apps-product-create',
      '/apps/product/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'apps-product-list': RouteRecordInfo<
      'apps-product-list',
      '/apps/product/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-authorized': RouteRecordInfo<
      'not-authorized',
      '/not-authorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'pages-account-settings-tab': RouteRecordInfo<
      'pages-account-settings-tab',
      '/pages/account-settings/:tab',
      { tab: ParamValue<true> },
      { tab: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...error].vue': {
      routes:
        | '$error'
      views:
        | never
    }
    'src/pages/access-control.vue': {
      routes:
        | 'access-control'
      views:
        | never
    }
    'src/pages/apps/account/address-management.vue': {
      routes:
        | 'apps-account-address-management'
      views:
        | never
    }
    'src/pages/apps/account/auth-management.vue': {
      routes:
        | 'apps-account-auth-management'
      views:
        | never
    }
    'src/pages/apps/account/fund-overview.vue': {
      routes:
        | 'apps-account-fund-overview'
      views:
        | never
    }
    'src/pages/apps/account/personalization.vue': {
      routes:
        | 'apps-account-personalization'
      views:
        | never
    }
    'src/pages/apps/account/tiktok-service.vue': {
      routes:
        | 'apps-account-tiktok-service'
      views:
        | never
    }
    'src/pages/apps/data-center/inventory-data.vue': {
      routes:
        | 'apps-data-center-inventory-data'
      views:
        | never
    }
    'src/pages/apps/data-center/return-inventory.vue': {
      routes:
        | 'apps-data-center-return-inventory'
      views:
        | never
    }
    'src/pages/apps/data-center/sales-analysis.vue': {
      routes:
        | 'apps-data-center-sales-analysis'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/begin.vue': {
      routes:
        | 'apps-drop-shipping-begin'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/order/batch.vue': {
      routes:
        | 'apps-drop-shipping-order-batch'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/order/create.vue': {
      routes:
        | 'apps-drop-shipping-order-create'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/order/detail.vue': {
      routes:
        | 'apps-drop-shipping-order-detail'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/order/list.vue': {
      routes:
        | 'apps-drop-shipping-order-list'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/order-label/create.vue': {
      routes:
        | 'apps-drop-shipping-order-label-create'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/order-label/detail.vue': {
      routes:
        | 'apps-drop-shipping-order-label-detail'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/order-label/list.vue': {
      routes:
        | 'apps-drop-shipping-order-label-list'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/package/batch.vue': {
      routes:
        | 'apps-drop-shipping-package-batch'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/package/create.vue': {
      routes:
        | 'apps-drop-shipping-package-create'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/package/detail.vue': {
      routes:
        | 'apps-drop-shipping-package-detail'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/package/list.vue': {
      routes:
        | 'apps-drop-shipping-package-list'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/return/order-batch.vue': {
      routes:
        | 'apps-drop-shipping-return-order-batch'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/return/order-create.vue': {
      routes:
        | 'apps-drop-shipping-return-order-create'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/return/order-detail.vue': {
      routes:
        | 'apps-drop-shipping-return-order-detail'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/return/order-list.vue': {
      routes:
        | 'apps-drop-shipping-return-order-list'
      views:
        | never
    }
    'src/pages/apps/drop-shipping/return/package-list.vue': {
      routes:
        | 'apps-drop-shipping-return-package-list'
      views:
        | never
    }
    'src/pages/apps/print-label/batch-upload.vue': {
      routes:
        | 'apps-print-label-batch-upload'
      views:
        | never
    }
    'src/pages/apps/print-label/create.vue': {
      routes:
        | 'apps-print-label-create'
      views:
        | never
    }
    'src/pages/apps/print-label/order-detail/[id].vue': {
      routes:
        | 'apps-print-label-order-detail-id'
      views:
        | never
    }
    'src/pages/apps/print-label/order-new-detail/[id].vue': {
      routes:
        | 'apps-print-label-order-new-detail-id'
      views:
        | never
    }
    'src/pages/apps/print-label/orders.vue': {
      routes:
        | 'apps-print-label-orders'
      views:
        | never
    }
    'src/pages/apps/print-label/shipping-list.vue': {
      routes:
        | 'apps-print-label-shipping-list'
      views:
        | never
    }
    'src/pages/apps/product/batch.vue': {
      routes:
        | 'apps-product-batch'
      views:
        | never
    }
    'src/pages/apps/product/create.vue': {
      routes:
        | 'apps-product-create'
      views:
        | never
    }
    'src/pages/apps/product/list.vue': {
      routes:
        | 'apps-product-list'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | 'dashboard'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/pages/not-authorized.vue': {
      routes:
        | 'not-authorized'
      views:
        | never
    }
    'src/pages/pages/account-settings/[tab].vue': {
      routes:
        | 'pages-account-settings-tab'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
